# Generated by Django 3.2.25 on 2024-06-14 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estrutura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='date_noticia',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='noticia',
            name='escritor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estrutura.escritor'),
            preserve_default=False,
        ),
    ]
