# Generated by Django 3.2.25 on 2024-06-18 12:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('materia', models.CharField(choices=[('FUTEBOL', 'Futebol'), ('OUTRO ESPORTE', 'Outro esporte')], default='', max_length=100)),
                ('corpo_texto', models.TextField(max_length=10000)),
                ('date_noticia', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('imagem_noticia', models.ImageField(blank=True, upload_to='./setup/static/assets/imagens/banco_imagens/')),
                ('imagem_fonte', models.CharField(blank=True, max_length=100)),
                ('publicada', models.BooleanField(default=False)),
                ('escritor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrutura.escritor')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
